services:
  - type: web
    name: my-flask-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: flask run --host=0.0.0.0 --port=5000
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
